package main

// TransactionState represents the state of a CHI transaction
type TransactionState string

const (
	TxStateInitiated TransactionState = "Initiated" // Transaction created
	TxStateInFlight  TransactionState = "InFlight"  // Transaction in progress
	TxStateCompleted TransactionState = "Completed" // Transaction completed successfully
	TxStateAborted   TransactionState = "Aborted"   // Transaction aborted
)

// DependencyType represents the type of dependency between transactions
type DependencyType string

const (
	// Causal dependency: Transaction B is directly triggered by Transaction A
	DepCausal DependencyType = "Causal"

	// Cache dependencies: Transaction B triggered due to Transaction A's cache operations
	DepCacheMiss       DependencyType = "CacheMiss"
	DepCacheEvict      DependencyType = "CacheEvict"
	DepCacheInvalidate DependencyType = "CacheInvalidate"

	// Ordering dependencies: Transaction B must wait for Transaction A to complete
	DepSameAddrOrdering DependencyType = "SameAddrOrdering"
	DepGlobalOrdering   DependencyType = "GlobalOrdering"

	// Directory dependencies: Transaction B needs to wait for Transaction A's directory operation
	DepDirectoryQuery  DependencyType = "DirectoryQuery"
	DepDirectoryUpdate DependencyType = "DirectoryUpdate"

	// Resource contention: Transaction B competes with Transaction A for the same resource
	DepResourceContention DependencyType = "ResourceContention"
)

// StateTransition represents a key state transition in a transaction's lifecycle
type StateTransition struct {
	Cycle        int              // Cycle when transition occurred
	FromState    TransactionState // Previous state
	ToState      TransactionState // New state
	Reason       string           // Reason for transition (brief description)
	RelatedTxnID *int64           // Related transaction ID (if any)
}

// TransactionContext represents the context of a CHI transaction
// Design principle: Only store essential information, detailed state queried via interfaces
type TransactionContext struct {
	// Basic information (must store)
	TransactionID   int64
	TransactionType CHITransactionType
	Address         uint64

	// State information (simplified)
	State        TransactionState
	StateHistory []StateTransition // Only record key state transition points
	InitiatedAt  int
	CompletedAt  int

	// Dependency relationships (must store, for graph construction)
	SameAddrOrdering      []int64 // Transaction IDs with same-address ordering dependency
	GlobalOrdering        []int64 // Transaction IDs with global ordering dependency
	GeneratedTransactions []int64 // Child transaction IDs generated by this transaction

	// Metadata (lightweight extension fields)
	Metadata map[string]string // Use string instead of interface{} to reduce storage
}

// Transaction represents a CHI protocol transaction
type Transaction struct {
	Context *TransactionContext
}

// TransactionDependency represents a dependency relationship between two transactions
type TransactionDependency struct {
	FromTransactionID int64          // Source transaction ID
	ToTransactionID   int64          // Target transaction ID
	DependencyType    DependencyType // Type of dependency
	Reason            string         // Reason for dependency (CacheMiss, SameAddrOrdering, etc.)
	Cycle             int            // Cycle when dependency was created
}

// CacheStateProvider interface: implemented by Cache module
// Core principle: Abstract model does not store cache/directory state directly, but queries via interfaces
type CacheStateProvider interface {
	// GetCacheState queries cache state for specified address
	GetCacheState(address uint64, nodeID int) (CacheState, bool)
	// GetCacheHit queries cache hit/miss result for specific transaction
	GetCacheHit(transactionID int64) *bool
	// GetCacheStateHistory queries cache state transition history (simplified)
	GetCacheStateHistory(transactionID int64) []CacheStateTransition
}

// DirectoryStateProvider interface: implemented by Directory module
type DirectoryStateProvider interface {
	// GetDirectoryState queries directory state for specified address
	GetDirectoryState(address uint64) DirectoryState
	// GetDirectoryHistory queries directory operation history (simplified)
	GetDirectoryHistory(transactionID int64) []DirectoryOperation
}

// OrderingConstraintProvider interface: implemented by Ordering module
type OrderingConstraintProvider interface {
	// GetSameAddrOrdering queries same-address ordering constraints
	GetSameAddrOrdering(address uint64) []int64 // Returns list of dependent transaction IDs
	// GetGlobalOrdering queries global ordering constraints
	GetGlobalOrdering(transactionID int64) []int64
	// GetOrderingDecisions queries ordering decision points
	GetOrderingDecisions(transactionID int64) []OrderingDecision
}

// Placeholder types for future implementation
// These will be implemented by other modules

// CacheState represents cache line state
type CacheState string

const (
	CacheStateInvalid CacheState = "Invalid"
	CacheStateShared  CacheState = "Shared"
	CacheStateUnique  CacheState = "Unique"
)

// CacheStateTransition represents a cache state transition
type CacheStateTransition struct {
	Cycle     int
	FromState CacheState
	ToState   CacheState
	Reason    string
}

// DirectoryState represents directory state
type DirectoryState string

const (
	DirectoryStateExclusive DirectoryState = "Exclusive"
	DirectoryStateShared    DirectoryState = "Shared"
	DirectoryStateInvalid   DirectoryState = "Invalid"
)

// DirectoryOperation represents a directory operation
type DirectoryOperation struct {
	Cycle     int
	Operation string
	Address   uint64
}

// OrderingDecision represents an ordering decision point
type OrderingDecision struct {
	Cycle       int
	Decision    string
	RelatedTxns []int64
}

// PacketEventType represents the type of packet event
type PacketEventType string

const (
	PacketEnqueued        PacketEventType = "PacketEnqueued"
	PacketDequeued        PacketEventType = "PacketDequeued"
	PacketProcessingStart PacketEventType = "PacketProcessingStart"
	PacketProcessingEnd   PacketEventType = "PacketProcessingEnd"
	PacketSent            PacketEventType = "PacketSent"
	PacketInTransitEnd    PacketEventType = "PacketInTransitEnd"
	PacketReceived        PacketEventType = "PacketReceived"
	PacketGenerated       PacketEventType = "PacketGenerated"
)

// PacketEvent represents a packet event in the transaction timeline
type PacketEvent struct {
	Sequence       int64             `json:"sequence"`
	TransactionID  int64             `json:"transactionID"`
	PacketID       int64             `json:"packetID"`
	ParentPacketID int64             `json:"parentPacketID"` // 0 means no parent packet
	NodeID         int               `json:"nodeID"`
	NodeLabel      string            `json:"nodeLabel"` // "RN 0", "SN 1", etc.
	EventType      PacketEventType   `json:"eventType"`
	Cycle          int               `json:"cycle"`
	EdgeKey        *EdgeKey          `json:"edgeKey,omitempty"` // nil for in-node events
	Metadata       map[string]string `json:"metadata,omitempty"`
}
