package core

// TransactionState represents the state of a CHI transaction.
type TransactionState string

const (
	TxStateInitiated TransactionState = "Initiated" // Transaction created
	TxStateInFlight  TransactionState = "InFlight"  // Transaction in progress
	TxStateCompleted TransactionState = "Completed" // Transaction completed successfully
	TxStateAborted   TransactionState = "Aborted"   // Transaction aborted
)

// DependencyType represents the type of dependency between transactions.
type DependencyType string

const (
	// Causal dependency: Transaction B is directly triggered by Transaction A
	DepCausal DependencyType = "Causal"

	// Cache dependencies: Transaction B triggered due to Transaction A's cache operations
	DepCacheMiss       DependencyType = "CacheMiss"
	DepCacheEvict      DependencyType = "CacheEvict"
	DepCacheInvalidate DependencyType = "CacheInvalidate"

	// Ordering dependencies: Transaction B must wait for Transaction A to complete
	DepSameAddrOrdering DependencyType = "SameAddrOrdering"
	DepGlobalOrdering   DependencyType = "GlobalOrdering"

	// Directory dependencies: Transaction B needs to wait for Transaction A's directory operation
	DepDirectoryQuery  DependencyType = "DirectoryQuery"
	DepDirectoryUpdate DependencyType = "DirectoryUpdate"

	// Resource contention: Transaction B competes with Transaction A for the same resource
	DepResourceContention DependencyType = "ResourceContention"
)

// StateTransition represents a key state transition in a transaction's lifecycle.
type StateTransition struct {
	Cycle        int              // Cycle when transition occurred
	FromState    TransactionState // Previous state
	ToState      TransactionState // New state
	Reason       string           // Reason for transition (brief description)
	RelatedTxnID *int64           // Related transaction ID (if any)
}

// TransactionContext represents the context of a CHI transaction.
// Design principle: Only store essential information, detailed state queried via interfaces.
type TransactionContext struct {
	// Basic information (must store)
	TransactionID   int64
	TransactionType CHITransactionType
	Address         uint64

	// State information (simplified)
	State        TransactionState
	StateHistory []StateTransition // Only record key state transition points
	InitiatedAt  int
	CompletedAt  int

	// Dependency relationships (must store, for graph construction)
	SameAddrOrdering      []int64 // Transaction IDs with same-address ordering dependency
	GlobalOrdering        []int64 // Transaction IDs with global ordering dependency
	GeneratedTransactions []int64 // Child transaction IDs generated by this transaction

	// Metadata (lightweight extension fields)
	Metadata map[string]string // Use string instead of interface{} to reduce storage
}

// Transaction represents a CHI protocol transaction.
type Transaction struct {
	Context *TransactionContext
}

// TransactionDependency represents a dependency relationship between two transactions.
type TransactionDependency struct {
	FromTransactionID int64          // Source transaction ID
	ToTransactionID   int64          // Target transaction ID
	DependencyType    DependencyType // Type of dependency
	Reason            string         // Reason for dependency (CacheMiss, SameAddrOrdering, etc.)
	Cycle             int            // Cycle when dependency was created
}


