// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package protocol

import (
	"encoding/json"
	"fmt"
)

// Defines values for CPUConfigType.
const (
	CPUConfigTypeChampsimO3 CPUConfigType = "champsim_o3"
	CPUConfigTypeCustom     CPUConfigType = "custom"
	CPUConfigTypeSimple     CPUConfigType = "simple"
)

// Defines values for CacheConfigReplacementPolicy.
const (
	FIFO   CacheConfigReplacementPolicy = "FIFO"
	LFU    CacheConfigReplacementPolicy = "LFU"
	LRU    CacheConfigReplacementPolicy = "LRU"
	Random CacheConfigReplacementPolicy = "Random"
)

// Defines values for EdgeDataLineType.
const (
	Dashed EdgeDataLineType = "dashed"
	Solid  EdgeDataLineType = "solid"
	Taxi   EdgeDataLineType = "taxi"
)

// Defines values for MemoryConfigType.
const (
	MemoryConfigTypeCustom MemoryConfigType = "custom"
	MemoryConfigTypeDdr4   MemoryConfigType = "ddr4"
	MemoryConfigTypeDdr5   MemoryConfigType = "ddr5"
	MemoryConfigTypeHbm    MemoryConfigType = "hbm"
)

// Defines values for NodeNodeType.
const (
	Cpu              NodeNodeType = "cpu"
	Generic          NodeNodeType = "generic"
	MemoryController NodeNodeType = "memory_controller"
	Router           NodeNodeType = "router"
)

// CPUConfig CPU 配置和统计
type CPUConfig struct {
	// BranchMispredictions 分支预测错误次数
	BranchMispredictions *int `json:"branch_mispredictions,omitempty"`

	// DecodeWidth Decode 宽度
	DecodeWidth *int `json:"decode_width,omitempty"`

	// DispatchWidth Dispatch 宽度
	DispatchWidth *int `json:"dispatch_width,omitempty"`

	// ExecuteWidth Execute 宽度
	ExecuteWidth *int `json:"execute_width,omitempty"`

	// FetchWidth Fetch 宽度
	FetchWidth *int `json:"fetch_width,omitempty"`

	// Ipc Instructions Per Cycle
	Ipc *float32 `json:"ipc,omitempty"`

	// L1dCache 缓存配置和统计
	L1dCache *CacheConfig `json:"l1d_cache,omitempty"`

	// LqSize Load Queue 大小
	LqSize *int `json:"lq_size,omitempty"`

	// RetireWidth Retire 宽度
	RetireWidth *int `json:"retire_width,omitempty"`

	// RobSize ROB 大小
	RobSize *int `json:"rob_size,omitempty"`

	// SqSize Store Queue 大小
	SqSize *int `json:"sq_size,omitempty"`

	// TotalCycles 总周期数
	TotalCycles *int `json:"total_cycles,omitempty"`

	// TotalInstructions 总指令数
	TotalInstructions *int `json:"total_instructions,omitempty"`

	// TraceFile Trace 文件路径
	TraceFile *string `json:"trace_file,omitempty"`

	// Type CPU 类型
	Type *CPUConfigType `json:"type,omitempty"`
}

// CPUConfigType CPU 类型
type CPUConfigType string

// CacheConfig 缓存配置和统计
type CacheConfig struct {
	// Accesses 总访问次数
	Accesses *int `json:"accesses,omitempty"`

	// Capacity 缓存容量（字节）
	Capacity int `json:"capacity"`

	// Hits 缓存命中次数
	Hits *int `json:"hits,omitempty"`

	// Misses 缓存未命中次数
	Misses *int `json:"misses,omitempty"`

	// NumSets 缓存组数
	NumSets int `json:"num_sets"`

	// ReplacementPolicy 替换策略
	ReplacementPolicy CacheConfigReplacementPolicy `json:"replacement_policy"`

	// States 一致性状态协议
	States string `json:"states"`
}

// CacheConfigReplacementPolicy 替换策略
type CacheConfigReplacementPolicy string

// DirectoryConfig 目录配置
type DirectoryConfig struct {
	Capacity          int    `json:"capacity"`
	NumSets           int    `json:"num_sets"`
	ReplacementPolicy string `json:"replacement_policy"`
	States            string `json:"states"`
}

// Edge 连接两个节点的边，兼容 CyEditor 格式
type Edge struct {
	// Bandwidth 链路带宽
	Bandwidth *int `json:"bandwidth,omitempty"`

	// Data CyEditor data 字段
	Data Edge_Data `json:"data"`

	// DstNodeId 目标节点 ID
	DstNodeId int `json:"dst_node_id"`

	// DstPortId 目标端口 ID
	DstPortId *int `json:"dst_port_id,omitempty"`

	// EdgeId 边唯一标识符
	EdgeId int `json:"edge_id"`

	// Latency 链路延迟（周期）
	Latency *int `json:"latency,omitempty"`

	// LinkStatus 链路占用状态
	LinkStatus *[]struct {
		// Name 状态名称（如 'occupancy'）
		Name string `json:"name"`

		// Values 每个时间槽的占用情况
		Values []int `json:"values"`
	} `json:"link_status,omitempty"`

	// PacketTypes 支持的包类型
	PacketTypes *[]int `json:"packet_types,omitempty"`

	// SrcNodeId 源节点 ID
	SrcNodeId int `json:"src_node_id"`

	// SrcPortId 源端口 ID
	SrcPortId *int `json:"src_port_id,omitempty"`
}

// EdgeDataLineType 线条类型
type EdgeDataLineType string

// Edge_Data CyEditor data 字段
type Edge_Data struct {
	// Id Cytoscape 边 ID（通常为 'edge-{edge_id}'）
	Id string `json:"id"`

	// LineType 线条类型
	LineType *EdgeDataLineType `json:"lineType,omitempty"`

	// Source 源节点 data.id
	Source string `json:"source"`

	// Target 目标节点 data.id
	Target               string                 `json:"target"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// FlowSimNetwork Flow Simulation 网络定义，包含拓扑、配置、状态和可视化信息
type FlowSimNetwork struct {
	// Cycle 当前仿真周期
	Cycle *int `json:"cycle,omitempty"`

	// Edges 边列表
	Edges []Edge `json:"edges"`

	// Nodes 节点列表
	Nodes []Node `json:"nodes"`

	// Pan 可选：视图平移（CyEditor）
	Pan *struct {
		X *float32 `json:"x,omitempty"`
		Y *float32 `json:"y,omitempty"`
	} `json:"pan,omitempty"`

	// Version Schema 版本号
	Version *string `json:"version,omitempty"`

	// Zoom 可选：视图缩放级别（CyEditor）
	Zoom *float32 `json:"zoom,omitempty"`
}

// MemoryConfig DRAM 控制器配置
type MemoryConfig struct {
	// Banks Bank 数
	Banks *int `json:"banks,omitempty"`

	// Channels 通道数
	Channels *int `json:"channels,omitempty"`

	// Columns 列数
	Columns *int `json:"columns,omitempty"`

	// Ranks Rank 数
	Ranks *int `json:"ranks,omitempty"`

	// ReadRequests 读请求数
	ReadRequests *int `json:"read_requests,omitempty"`

	// RowBufferHits Row Buffer 命中数
	RowBufferHits *int `json:"row_buffer_hits,omitempty"`

	// RowBufferMisses Row Buffer 未命中数
	RowBufferMisses *int `json:"row_buffer_misses,omitempty"`

	// Rows 行数
	Rows *int `json:"rows,omitempty"`

	// TCAS CAS Latency
	TCAS *int `json:"tCAS,omitempty"`

	// TRAS Row Active Time
	TRAS *int `json:"tRAS,omitempty"`

	// TRCD RAS to CAS Delay
	TRCD *int `json:"tRCD,omitempty"`

	// TRP Row Precharge Time
	TRP *int `json:"tRP,omitempty"`

	// Type 内存类型
	Type *MemoryConfigType `json:"type,omitempty"`

	// WriteRequests 写请求数
	WriteRequests *int `json:"write_requests,omitempty"`
}

// MemoryConfigType 内存类型
type MemoryConfigType string

// Node 网络节点，兼容 CyEditor 格式
type Node struct {
	// Cache 缓存配置和统计
	Cache *CacheConfig `json:"cache,omitempty"`

	// CoherenceDomainId 一致性域 ID
	CoherenceDomainId *int `json:"coherence_domain_id,omitempty"`

	// CpuConfig CPU 配置和统计
	CpuConfig *CPUConfig `json:"cpu_config,omitempty"`

	// Data CyEditor data 字段，存储节点元数据
	Data Node_Data `json:"data"`

	// Directory 目录配置
	Directory *DirectoryConfig `json:"directory,omitempty"`

	// InPorts 输入端口列表
	InPorts *[]Port `json:"in_ports,omitempty"`

	// MemoryConfig DRAM 控制器配置
	MemoryConfig *MemoryConfig `json:"memory_config,omitempty"`

	// NodeFeatures 节点特性列表，如 ['cpu', 'cache']
	NodeFeatures *[]string `json:"node_features,omitempty"`

	// NodeId 节点唯一标识符
	NodeId int `json:"node_id"`

	// NodeName 节点名称
	NodeName string `json:"node_name"`

	// NodeType 节点类型
	NodeType *NodeNodeType `json:"node_type,omitempty"`

	// OutPorts 输出端口列表
	OutPorts *[]Port `json:"out_ports,omitempty"`

	// Position CyEditor position 字段
	Position struct {
		X float32 `json:"x"`
		Y float32 `json:"y"`
	} `json:"position"`

	// Style Cytoscape 样式
	Style *map[string]interface{} `json:"style,omitempty"`
}

// Node_Data CyEditor data 字段，存储节点元数据
type Node_Data struct {
	// Id Cytoscape 节点 ID（通常为 'node-{node_id}'）
	Id string `json:"id"`

	// Label 节点显示标签
	Label *string `json:"label,omitempty"`

	// Type 节点类型（用于渲染）
	Type                 *string                `json:"type,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NodeNodeType 节点类型
type NodeNodeType string

// Port 端口定义，包含配置和运行时状态
type Port struct {
	// Bandwidth 带宽（配置）
	Bandwidth int `json:"bandwidth"`

	// Bitmap 缓冲区占用位图，如 '1010...'
	Bitmap *string `json:"bitmap,omitempty"`

	// BufferLength 当前缓冲区使用量
	BufferLength *int `json:"buffer_length,omitempty"`

	// BufferSize 缓冲区大小（配置）
	BufferSize *int `json:"buffer_size,omitempty"`

	// Capacity 缓冲区容量（别名，与 buffer_size 相同）
	Capacity *int `json:"capacity,omitempty"`

	// PacketTypes 支持的包类型
	PacketTypes *[]int `json:"packet_types,omitempty"`

	// PortId 端口 ID
	PortId int `json:"port_id"`
}

// PostAdvanceToJSONBody defines parameters for PostAdvanceTo.
type PostAdvanceToJSONBody struct {
	// Cycle 目标仿真周期
	Cycle int `json:"cycle"`
}

// PostLoadPresetJSONBody defines parameters for PostLoadPreset.
type PostLoadPresetJSONBody struct {
	// Name 预设名称
	Name string `json:"name"`

	// Params 预设参数
	Params *map[string]interface{} `json:"params,omitempty"`
}

// PostSaveNetworkJSONBody defines parameters for PostSaveNetwork.
type PostSaveNetworkJSONBody struct {
	// Name 文件名
	Name string `json:"name"`

	// Network Flow Simulation 网络定义，包含拓扑、配置、状态和可视化信息
	Network FlowSimNetwork `json:"network"`
}

// PostAdvanceToJSONRequestBody defines body for PostAdvanceTo for application/json ContentType.
type PostAdvanceToJSONRequestBody PostAdvanceToJSONBody

// PostBuildNetworkJSONRequestBody defines body for PostBuildNetwork for application/json ContentType.
type PostBuildNetworkJSONRequestBody = FlowSimNetwork

// PostLoadPresetJSONRequestBody defines body for PostLoadPreset for application/json ContentType.
type PostLoadPresetJSONRequestBody PostLoadPresetJSONBody

// PostResetNetworkJSONRequestBody defines body for PostResetNetwork for application/json ContentType.
type PostResetNetworkJSONRequestBody = FlowSimNetwork

// PostSaveNetworkJSONRequestBody defines body for PostSaveNetwork for application/json ContentType.
type PostSaveNetworkJSONRequestBody PostSaveNetworkJSONBody

// PostValidateNetworkJSONRequestBody defines body for PostValidateNetwork for application/json ContentType.
type PostValidateNetworkJSONRequestBody = FlowSimNetwork

// Getter for additional properties for Edge_Data. Returns the specified
// element and whether it was found
func (a Edge_Data) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Edge_Data
func (a *Edge_Data) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Edge_Data to handle AdditionalProperties
func (a *Edge_Data) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["lineType"]; found {
		err = json.Unmarshal(raw, &a.LineType)
		if err != nil {
			return fmt.Errorf("error reading 'lineType': %w", err)
		}
		delete(object, "lineType")
	}

	if raw, found := object["source"]; found {
		err = json.Unmarshal(raw, &a.Source)
		if err != nil {
			return fmt.Errorf("error reading 'source': %w", err)
		}
		delete(object, "source")
	}

	if raw, found := object["target"]; found {
		err = json.Unmarshal(raw, &a.Target)
		if err != nil {
			return fmt.Errorf("error reading 'target': %w", err)
		}
		delete(object, "target")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Edge_Data to handle AdditionalProperties
func (a Edge_Data) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.LineType != nil {
		object["lineType"], err = json.Marshal(a.LineType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'lineType': %w", err)
		}
	}

	object["source"], err = json.Marshal(a.Source)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source': %w", err)
	}

	object["target"], err = json.Marshal(a.Target)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'target': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Node_Data. Returns the specified
// element and whether it was found
func (a Node_Data) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Node_Data
func (a *Node_Data) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Node_Data to handle AdditionalProperties
func (a *Node_Data) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["label"]; found {
		err = json.Unmarshal(raw, &a.Label)
		if err != nil {
			return fmt.Errorf("error reading 'label': %w", err)
		}
		delete(object, "label")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Node_Data to handle AdditionalProperties
func (a Node_Data) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.Label != nil {
		object["label"], err = json.Marshal(a.Label)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'label': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
